### ISSUE TITLE
Libssh, unable to port forwarding

### ISSUE THREAD

**Issue by Alecaddd** [apmasell/vapis#7]
Hello, thank you so much for providing the `libssh2.vapi` as it has been extremely useful for Sequeler, my SQL client app built in Vala.
I'm currently facing an issue where I can't seem to make the Port Forwarding feature work, and I'm not sure if I'm doing something wrong or what I'm trying to achieve is currently not supported by the vapi.

I know I shouldn't open this issue as it's not really an issue related to your vapi, but I couldn't find any help regarding this topic anywhere.
Here's the portion of my code which handles the SSH connection, and you can see my attempt to do a port forwarding at line `176`.
https://github.com/Alecaddd/sequeler/blob/dev/src/Services/ConnectionManager.vala#L111

I would be really grateful if you could take a quick look and let me know if I'm doing something wrong, or simply pushing me towards the right direction.

Cheers,

**Comment by apmasell** [comment]
The `SSH2.Listener` is your forwarded port. You have to do `listener.accept()` to get a new `Channel` that is your connection to the client on the remote machine. When the listener goes out of scope, the forwarded port is closed.

**Comment by Alecaddd** [comment]
Thank you so much for the quick response.
Unfortunately, it doesn't seem to be able to get the new channel when I run `listener.accept()`.
The application hangs on that state waiting for the async method to complete, and I have to manually shut it down. 
I waited 15 minutes just to be sure it wasn't just my server being super slow.

**Comment by apmasell** [comment]
I've never used this functionality, so I don't know. Sorry.
